// paymentBridge.js — Upgraded to v0.4 ES Module standard with native @solana/web3.js integration
import { Connection, PublicKey } from '@solana/web3.js';

// Establishing the core Solana network connection context (Using public Devnet for local sandboxing)
const SOLANA_RPC_ENDPOINT = process.env.SOLANA_RPC_URL || "https://solana.com";
const connection = new Connection(SOLANA_RPC_ENDPOINT, "confirmed");

// Protocol fee configuration parameters
const PROTOCOL_FEE_RATE = 0.02; // 2% protocol treasury share

/**
 * 🔥 PART III: NATIVE SOLANA TRANSACTION VERIFICATION ENGINE 🔥
 * Cross-examines a transaction signature directly on the Solana blockchain network.
 * Verifies that the collector physically transferred the required currency tokens.
 *
 * @param {string} signature - The raw transaction signature string generated by the Phantom wallet.
 * @param {string} artistWalletStr - The destination public key address string of the publishing artist.
 * @param {number} expectedAmountLamports - The required track cost calculated in Lamports (1 SOL = 10^9 Lamports).
 * @returns {Promise<boolean>}
 */
export async function verifySolanaPayment(signature, artistWalletStr, expectedAmountLamports) {
    console.log(`📡 Querying Solana ledger... Verifying transaction signature: ${signature}`);

    try {
        if (!signature) return false;

        // 1. Fetch the confirmed transaction record directly off the Solana network blocks
        const txInfo = await connection.getTransaction(signature, {
            maxSupportedTransactionVersion: 0
        });

        if (!txInfo) {
            console.error("❌ Solana payment verification rejected: Transaction signature not found on the network.");
            return false;
        }

        // 2. Validate that the payment transaction executed successfully with zero inner script errors
        if (txInfo.meta && txInfo.meta.err) {
            console.error("❌ Solana payment verification rejected: Transaction flagged as failed on-chain execution.");
            return false;
        }

        // 3. Extract the physical transaction account index mappings
        const accountKeys = txInfo.transaction.message.getAccountKeys
            ? txInfo.transaction.message.getAccountKeys().staticAccountKeys
            : txInfo.transaction.message.accountKeys;

        // 4. Verify that the target artist's public key address was a recipient in this transaction
        const artistPubKey = new PublicKey(artistWalletStr);
        const artistAccountIndex = accountKeys.findIndex(key => key.equals(artistPubKey));

        if (artistAccountIndex === -1) {
            console.error(`❌ Solana payment verification rejected: Artist wallet ${artistWalletStr} was not an account recipient.`);
            return false;
        }

        // 5. Evaluate the net change in Lamports to verify the artist received their equity share
        const postBalance = txInfo.meta.postBalances[artistAccountIndex];
        const preBalance = txInfo.meta.preBalances[artistAccountIndex];
        const netReceivedLamports = postBalance - preBalance;

        // Calculate expected split margins: subtract the 2% protocol fee from the absolute price tag
        const expectedTreasuryShare = expectedAmountLamports * PROTOCOL_FEE_RATE;
        const expectedArtistShare = expectedAmountLamports - expectedTreasuryShare;

        if (netReceivedLamports < expectedArtistShare) {
            console.error(`❌ Balance delta mismatch! Expected artist share: ${expectedArtistShare} Lamports, received: ${netReceivedLamports}.`);
            return false;
        }

        console.log(`✓ [Payment Bridge] Verified Solana signature successful! Net settlement: ${(netReceivedLamports / 1e9).toFixed(4)} SOL transferred to artist.`);
        return true;
    } catch (err) {
        console.error("❌ Solana payment verification engine crashed:", err.message);
        return false;
    }
}

/**
 * Main orchestration entry point.
 * Coordinates verified payment validation before triggering local social database mutations.
 */
export async function handlePaymentProcessing(registry, paymentDetails) {
    console.log("--- Starting Cryptographic Payment Orchestration ---");

    const { signature, artistWallet, amountLamports } = paymentDetails;

    // Execute the live on-chain cross-examination routine
    const isVerified = await verifySolanaPayment(signature, artistWallet, amountLamports);

    if (!isVerified) {
        throw new Error("Solana payment verification failed. Access to registry tracking blocked.");
    }

    // Dynamic import to prevent dependency boot lag
    const { processTip } = await import('./social.js');

    // Convert lamports to clean decimal tokens for historical registry ledger recording
    const decimalSolAmount = amountLamports / 1e9;
    const treasuryShare = decimalSolAmount * PROTOCOL_FEE_RATE;
    const netArtistAmount = decimalSolAmount - treasuryShare;

    return processTip(registry, paymentDetails.sender, netArtistAmount);
}
